name: heart-disease-predictor
channels:
    - default
    - anaconda
    - conda-forge

dependencies:
    - python=3.6
    - pandas
    - scikit-learn
    - boto3
    - numpy
    - pip
    - pip:
      - mlflow>=1.0